### ISSUE TITLE
BLACK MIRROR - Bandersnatch Interactive Player ( based on html5 video player)

### ISSUE THREAD

**Issue by mehotkhan** [joric/bandersnatch#1]
i create this , based on your work
https://github.com/mehotkhan/BandersnatchInteractive

**Comment by joric** [comment]
Superb

**Comment by joric** [comment]
Oh it can work online, super cool. So you don't need to host anything, just open the page, https://mehotkhan.github.io/BandersnatchInteractive/ and drag an mkv file there. Nice! Added to references in e7910fd1.

**Comment by CyberShadow** [comment]
Hi, I've been sending [some improvements](https://github.com/mehotkhan/BandersnatchInteractive/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3ACyberShadow+) to @mehotkhan's project, and just now realized you are the original author of the code. (Perhaps I should have been sending fixes to this repository instead?) As the original author, would you be OK with releasing the code under the MIT license? I think it would be good to have a fully open-source player for the data files.

**Comment by joric** [comment]
@CyberShadow cool. Yeah sure. I was hoping it gets better with better controls but I don't have time.
f3a58d84

**Comment by CyberShadow** [comment]
Thanks! I may keep working on it for a bit. My goal is at least to ensure that all branches are reachable, maybe then improve cosmetics to make it more like the original next.
