### ISSUE TITLE
Subtitle not showing problem

### ISSUE THREAD

**Issue by MehmetNY** [joric/bandersnatch#2]
Hello, first, I appreciate your work and thank you.

I did everything you said and it worked.

But I can't show subtitles like @mehotkhan 's online player. (_maybe working because it's online_)

**Can you tell me how I can open subtitles offline** (_in your project_).

=_Let me tell you before you ask; I've already tried the vtt format._=

**Comment by joric** [comment]
Yeah they don't load without a local server, it's a content-origin thing. You can also run browser as `chrome.exe --allow-file-access-from-files`, that works too.
