### ISSUE TITLE
Can we add multiple audios?

### ISSUE THREAD

**Issue by cemalgulbeyaz** [joric/bandersnatch#3]
I tried some things with PlayerJS but it didnt work.
My point is add to audio track from in mkv tracks or external mka files. Is it possible?

**Comment by joric** [comment]
You could try implementing something like that:

https://gingertech.net/2011/05/01/html5-multi-track-audio-or-video/

```
<video id="v1" poster=“video.png” controls>
 <source src=“video.ogv” type=”video/ogg”>
 <source src=“video.mp4” type=”video/mp4”>
</video>

<script type="text/javascript">
video = document.getElementsByTagName("video")[0];

for (i=0; i < video.audioTracks.length; i++) {
  if (video.audioTracks[i].language.substring(0,2) === "fr") {
    video.audioTracks[i].enabled = true;
  } else {
    video.audioTracks[i].enabled = false;
  }
}
</script>
```

**Comment by cemalgulbeyaz** [comment]
i saw that example when i research aboout it but there are some codes about interface and i dont know where i put that interface codes. I tried to put in javascript codes but it gave error about syntax (i using Visual Studio be editor and i putted interface codes to script tags in HTML) Can you help me about tahat interface codes?
`interface HTMLMediaElement : HTMLElement {
  [...]
  // tracks
  readonly attribute AudioTrackList audioTracks;
  readonly attribute VideoTrackList videoTracks;
};

interface AudioTrackList : EventTarget {
  readonly attribute unsigned long length;
  getter AudioTrack (unsigned long index);
  AudioTrack? getTrackById(DOMString id);

           attribute EventHandler onchange;
           attribute EventHandler onaddtrack;
           attribute EventHandler onremovetrack;
};

interface AudioTrack {
  readonly attribute DOMString id;
  readonly attribute DOMString kind;
  readonly attribute DOMString label;
  readonly attribute DOMString language;
           attribute boolean enabled;
};

interface VideoTrackList : EventTarget {
  readonly attribute unsigned long length;
  getter VideoTrack (unsigned long index);
  VideoTrack? getTrackById(DOMString id);
  readonly attribute long selectedIndex;

           attribute EventHandler onchange;
           attribute EventHandler onaddtrack;
           attribute EventHandler onremovetrack;
};

interface VideoTrack {
  readonly attribute DOMString id;
  readonly attribute DOMString kind;
  readonly attribute DOMString label;
  readonly attribute DOMString language;
           attribute boolean selected;
};`

**Comment by joric** [comment]
Don't know really. Consider it's an old abandoned project. Feel free to rewrite it.

**Comment by cemalgulbeyaz** [comment]
I think i found the problem: that interface codes seems for browsers, Audiotracks work with microsoft edge browser but not working with chrome and mozilla. I was using chromium for your project because my video file is HEVC (x265) mkv this not working with other browsers. I have no idea what can i do for AudioTrack change in Chromium.
